title: 개발자의 기술 블로그
email: jcm03141@gmail.com
description: >- 
  개발과 기술에 대한 이야기를 나누는 공간입니다.
  웹 개발, 모바일 앱, 인공지능 등 다양한 기술에 대한 
  경험과 지식을 공유합니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jcm0314.github.io" # the base hostname & protocol for your site
github_username:  jcm0314

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Google Analytics
google_analytics: G-XXXXXXXXXX  # Google Analytics 4 측정 ID를 여기에 입력하세요

# Social Media
twitter_username: your-twitter-username
github_username: jcm0314

# Comments
disqus_shortname: your-disqus-shortname  # Disqus shortname을 여기에 입력하세요

# Search
search_enabled: true

# Theme
dark_mode_enabled: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 