title: 짱천명명
email: jcm03141@gmail.com
description: >- 
  GitHub Pages를 사용한 짱천명 개인 블로그입니다.
  기술, 개발, 일상에 대한 글을 작성합니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jcm0314.github.io" # the base hostname & protocol for your site
github_username:  jcm0314

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 